/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "base-white": "#ffffff",
        "base-background": "#fafafa",
        "base-card": "#f3f2f2",
        "base-input": "#ededed",
        "base-button": "#e6e5e5",
        "base-hover": "#d7d5d5",
        "base-label": "#8d8686",
        "base-text": "#574f4d",
        "base-subtitle": "#403937",
        "base-title": "#272221",
        "base-error": "#f84747",
        "brand-purple-dark": "#4b2995",
        "brand-purple": "#8047f8",
        "brand-purple-light": "#ebe5f9",
        "brand-yellow-dark": "#c47f17",
        "brand-yellow": "#dbac2c",
        "brand-yellow-light": "#f1e9c9",
      },
    },
    sizes: {
      "size-title-title-xl": "3rem",
      "size-title-title-l": "2rem",
      "size-title-title-m": "1.5rem",
      "size-title-title-s": "1.2rem",
      "size-title-title-xs": "1.125rem",
      "size-text-regular-l": "1.25rem",
      "size-text-bold-l": "1.25rem",
      "size-text-regular-m": "1rem",
      "size-text-bold-m": "1rem",
      "size-text-regular-s": "0.875rem",
      "size-text-bold-s": "0.75rem",
      "size-components-tag": "0.625rem",
      "size-components-button-g": "0.875rem",
      "size-components-button-s": "0.75rem",
    },
  },
  plugins: [],
};
